name=John
age=26

url = https://testautomationpractice.blogspot.com/
browser = chrome
#browser = FF

name = David
email = david@gmail.com
phone = 9876543210
address = London

###Object repository ###

name_xpath = //*[@id='name']
email_xpath = //*[@id='email']
phone_xpath = //*[@id='phone']
address_xpath = //*[@id='textarea']

